section .asm

extern interrupt_handler
extern no_interrupt_handler
extern isr80h_handler

global idt_load
global no_interrupt
global isr80h_wrapper
global enable_interrupts
global disable_interrupts
global interrupt_pointer_table

idt_load:
    push ebp
    mov ebp, esp
    mov ebx, [ebp+8]
    lidt [ebx]
    pop ebp
    ret

no_interrupt:
    pushad
    call no_interrupt_handler
    popad
    iret

; Ch 102 isr80h_wrapper - the int 0x80 entry point user processes will
; call to ask the kernel to do something. The CPU has already pushed
; the user-side ip/cs/flags/esp/ss onto the kernel stack when this
; runs.
isr80h_wrapper:
    ; Push the user general-purpose registers in the order C's
    ; struct interrupt_frame expects: edi, esi, ebp, esp(reserved),
    ; ebx, edx, ecx, eax.
    pushad

    ; Pass the address of the interrupt frame (current ESP) as the
    ; second argument to the C handler.
    push esp

    ; Pass the command number (the user's pre-trap EAX, which pushad
    ; already saved at offset 28 of the frame).
    push eax

    call isr80h_handler

    ; Stash the handler's return value before popad clobbers EAX.
    mov dword [tmp_res], eax

    ; Pop the two arguments we pushed.
    add esp, 8

    ; Restore the user GPRs.
    popad

    ; Reload EAX with the syscall return value so the user code sees it.
    mov eax, [tmp_res]
    iretd

; Ch 112: one assembly stub per interrupt vector, generated by a NASM
; macro. Each stub pushes the GPRs (struct interrupt_frame layout),
; passes the frame ptr + interrupt number to the C interrupt_handler,
; then restores and returns. No more hand-rolling asm per IRQ.
%macro interrupt 1
    global int%1
    int%1:
        ; INTERRUPT FRAME START - the CPU has already pushed:
        ;   ip, cs, flags, sp, ss
        pushad
        ; INTERRUPT FRAME END

        push esp           ; struct interrupt_frame*
        push dword %1      ; interrupt number
        call interrupt_handler
        add  esp, 8

        popad
        iret
%endmacro

%assign i 0
%rep 512
    interrupt i
%assign i i+1
%endrep

enable_interrupts:
    sti
    ret

disable_interrupts:
    cli
    ret

section .data
; Stash for isr80h_handler's return value across popad.
tmp_res: dd 0

; Table of pointers to int0..int511 stubs. idt.c walks this to install
; every IDT vector via idt_set.
%macro interrupt_array_entry 1
    dd int%1
%endmacro

interrupt_pointer_table:
%assign i 0
%rep 512
    interrupt_array_entry i
%assign i i+1
%endrep
