section .asm

extern interrupt_handler
extern no_interrupt_handler
extern isr80h_handler

global idt_load
global no_interrupt
global isr80h_wrapper
global enable_interrupts
global disable_interrupts
global interrupt_pointer_table

; Lecture 35 - 64-bit pushad / popad.
;
; x86_64 dropped the 1-insn pushad/popad helpers. We emulate them
; via macros so the rest of idt.asm keeps reading like the 32-bit
; original; only the body of each macro is hand-rolled.
;
; The 32-bit pushad pushed 8 32-bit regs in the order
;   eax, ecx, edx, ebx, esp, ebp, esi, edi
; popad consumes them in reverse but DISCARDS the saved esp
; (popad's third pop is to nothing, then rsp is restored from the
; original frame).
;
; Our 64-bit version preserves the same order at register width:
; we stash the current rsp in a static slot, push rax..rdi in the
; same order, then on popad pop in reverse and restore rsp from
; the stash. The push of rsp itself is a pushed COPY (the value
; the stack pointer had ON ENTRY to pushad_macro) so the layout
; mirrors 32-bit pushad's expectations - C handlers that interpret
; the frame as a struct see rsp at the same slot they used to see
; esp.
;
; L36 will widen the rest of the file (push esp -> push rsp,
; iret -> iretq, the interrupt_pointer_table entries from dd to
; dq, etc).
temp_rsp_storage: dq 0x00

%macro pushad_macro 0
    mov qword [temp_rsp_storage], rsp
    push rax
    push rcx
    push rdx
    push rbx
    push qword [temp_rsp_storage]   ; rsp slot (32-bit pushad esp)
    push rbp
    push rsi
    push rdi
%endmacro

%macro popad_macro 0
    pop rdi
    pop rsi
    pop rbp
    pop qword [temp_rsp_storage]    ; discard pushed rsp
    pop rbx
    pop rdx
    pop rcx
    pop rax
    mov rsp, [temp_rsp_storage]
%endmacro

idt_load:
    push ebp
    mov ebp, esp
    mov ebx, [ebp+8]
    lidt [ebx]
    pop ebp
    ret

no_interrupt:
    pushad_macro
    call no_interrupt_handler
    popad_macro
    iret

; Ch 102 isr80h_wrapper - the int 0x80 entry point user processes will
; call to ask the kernel to do something. The CPU has already pushed
; the user-side ip/cs/flags/esp/ss onto the kernel stack when this
; runs.
isr80h_wrapper:
    ; Push the user general-purpose registers in the order C's
    ; struct interrupt_frame expects: edi, esi, ebp, esp(reserved),
    ; ebx, edx, ecx, eax.
    pushad_macro

    ; Pass the address of the interrupt frame (current ESP) as the
    ; second argument to the C handler.
    push esp

    ; Pass the command number (the user's pre-trap EAX, which pushad
    ; already saved at offset 28 of the frame).
    push eax

    call isr80h_handler

    ; Stash the handler's return value before popad clobbers EAX.
    mov dword [tmp_res], eax

    ; Pop the two arguments we pushed.
    add esp, 8

    ; Restore the user GPRs.
    popad_macro

    ; Reload EAX with the syscall return value so the user code sees it.
    mov eax, [tmp_res]
    iretd

; Ch 112: one assembly stub per interrupt vector, generated by a NASM
; macro. Each stub pushes the GPRs (struct interrupt_frame layout),
; passes the frame ptr + interrupt number to the C interrupt_handler,
; then restores and returns. No more hand-rolling asm per IRQ.
%macro interrupt 1
    global int%1
    int%1:
        ; INTERRUPT FRAME START - the CPU has already pushed:
        ;   ip, cs, flags, sp, ss
        pushad_macro
        ; INTERRUPT FRAME END

        push esp           ; struct interrupt_frame*
        push dword %1      ; interrupt number
        call interrupt_handler
        add  esp, 8

        popad_macro
        iret
%endmacro

%assign i 0
%rep 512
    interrupt i
%assign i i+1
%endrep

enable_interrupts:
    sti
    ret

disable_interrupts:
    cli
    ret

section .data
; Stash for isr80h_handler's return value across popad.
tmp_res: dd 0

; Table of pointers to int0..int511 stubs. idt.c walks this to install
; every IDT vector via idt_set.
%macro interrupt_array_entry 1
    dd int%1
%endmacro

interrupt_pointer_table:
%assign i 0
%rep 512
    interrupt_array_entry i
%assign i i+1
%endrep
