#ifndef ISR80H_H
#define ISR80H_H

enum SystemCommands {
    SYSTEM_COMMAND0_SUM,
    SYSTEM_COMMAND1_PRINT,
    SYSTEM_COMMAND2_GETKEY,
    SYSTEM_COMMAND3_PUTCHAR,
    SYSTEM_COMMAND4_MALLOC,
    SYSTEM_COMMAND5_FREE,
    SYSTEM_COMMAND6_PROCESS_LOAD_START,
    SYSTEM_COMMAND7_INVOKE_SYSTEM_COMMAND,
    SYSTEM_COMMAND8_GET_PROGRAM_ARGUMENTS,
    SYSTEM_COMMAND9_EXIT,
    SYSTEM_COMMAND10_FOPEN,  // L105 - userland fopen
    SYSTEM_COMMAND11_FCLOSE, // L106 - userland fclose
    SYSTEM_COMMAND12_FREAD,  // L107 - userland fread
    SYSTEM_COMMAND13_FSEEK,  // L111 - userland fseek
    SYSTEM_COMMAND14_FSTAT,  // L112 - userland fstat
    SYSTEM_COMMAND15_REALLOC, // L115 - userland realloc
    SYSTEM_COMMAND16_WINDOW_CREATE, // L154 - userland window create
};

void isr80h_register_commands();

#endif
