#ifndef CONFIG_H
#define CONFIG_H

#define KERNEL_CODE_SELECTOR    0x08
#define KERNEL_DATA_SELECTOR    0x10

#define SAMOS_TOTAL_INTERRUPTS  512

// 100 MiB heap.
#define SAMOS_HEAP_SIZE_BYTES   104857600
#define SAMOS_HEAP_BLOCK_SIZE   4096
#define SAMOS_HEAP_ADDRESS      0x01000000
#define SAMOS_HEAP_TABLE_ADDRESS 0x00007E00

#define SAMOS_SECTOR_SIZE       512

#define SAMOS_MAX_FILESYSTEMS        12
#define SAMOS_MAX_FILE_DESCRIPTORS  512

#define SAMOS_TOTAL_GDT_SEGMENTS     6

#define SAMOS_PROGRAM_VIRTUAL_ADDRESS                       0x400000
#define SAMOS_USER_PROGRAM_STACK_SIZE                       (1024 * 16)
#define SAMOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START           0x3FF000
#define SAMOS_PROGRAM_VIRTUAL_STACK_ADDRESS_END             (SAMOS_PROGRAM_VIRTUAL_STACK_ADDRESS_START - SAMOS_USER_PROGRAM_STACK_SIZE)

#define USER_DATA_SEGMENT       0x23
#define USER_CODE_SEGMENT       0x1B

#define SAMOS_MAX_PROGRAM_ALLOCATIONS    1024
#define SAMOS_MAX_PROCESSES              12

#endif
